embulk-input-marketo.gemspec, lib/embulk/input/marketo.rb, lib/embulk/input/marketo_api.rb, lib/embulk/input/marketo_api/soap.rb, test/embulk/input/test_marketo.rb, test/lead_fixtures.rb
I implemented run command (also preview command).
Some TODOs are remaining yet, I'll implemented them by the PRs Later.
NOTE: This implementaion needs Embulk 0.6.13 or later, so README shows this version before release 0.0.1.
=> Implement run/preview command

.travis.yml, Rakefile, embulk-input-marketo.gemspec, gemfiles/embulk-0.6.16, gemfiles/embulk-0.6.17, gemfiles/embulk-0.6.18, gemfiles/embulk-0.6.19, gemfiles/embulk-0.6.20, gemfiles/embulk-0.6.21, gemfiles/embulk-0.6.22, gemfiles/embulk-0.6.23, gemfiles/embulk-0.6.24, gemfiles/embulk-0.6.25, gemfiles/embulk-latest, gemfiles/template.erb
- remove duplicated task (`release:prepare` -> `generate:prepare_release`)
- execute `rake generate:gemfiles MIN_VERSION=0.6.16` and add setting for them to `.travis.yml`
=> Use everyleaf embulk helper

lib/embulk/input/marketo/activity_log.rb, lib/embulk/input/marketo/base.rb, lib/embulk/input/marketo_api/soap/activity_log.rb, test/activity_log_fixtures.rb, test/embulk/input/marketo/test_activity_log.rb, test/embulk/input/marketo/test_base.rb, test/embulk/input/marketo_api/soap/test_activity_log.rb
=> Support scheduled execution

lib/embulk/input/marketo/lead.rb, test/embulk/input/marketo/test_lead.rb
- guessing timestamp column was wrong (guessed as string)
- Do Time.parse for timestamp column to tell Embulk
=> Fix timestamp column

README.md, lib/embulk/input/marketo/activity_log.rb, lib/embulk/input/marketo/lead.rb, lib/embulk/input/marketo_api/soap/base.rb
- Fix to pass Time object to Embulk page_builder
- Fix reviewed points on https://github.com/treasure-data/embulk-input-marketo/pull/25#issuecomment-135629945
=> Fix minor issues

lib/embulk/input/marketo_api/soap/base.rb, test/embulk/input/marketo_api/soap/test_base.rb
=> Retry to call API until 5 times when Timeout::Error is raised

README.md, embulk-input-marketo.gemspec, lib/embulk/input/marketo/activity_log.rb, lib/embulk/input/marketo/base.rb, lib/embulk/input/marketo_api/soap/activity_log.rb, lib/embulk/input/marketo_api/soap/base.rb, test/embulk/input/marketo/test_activity_log.rb, test/embulk/input/marketo/test_base.rb
=> From to filter for activity log

lib/embulk/input/marketo_api/soap/activity_log.rb, test/embulk/input/marketo_api/soap/test_activity_log.rb
=> activity_log: Use from..from+30m range for guess

README.md, lib/embulk/input/marketo/activity_log.rb, lib/embulk/input/marketo/lead.rb, lib/embulk/input/marketo_api/soap/activity_log.rb, lib/embulk/input/marketo_api/soap/base.rb, lib/embulk/input/marketo_api/soap/lead.rb, test/embulk/input/marketo/test_activity_log.rb, test/embulk/input/marketo/test_lead.rb, test/embulk/input/marketo_api/soap/test_base.rb, test/embulk/input/marketo_api/soap/test_lead.rb
Add `retry_initial_wait_sec` and `retry_limit` options described on README.
=> Exponential backoff retry

.travis.yml, .travis.yml.erb, Rakefile, test/run-test.rb
=> Gathering test coverage on CI

lib/embulk/input/marketo/activity_log.rb, lib/embulk/input/marketo/base.rb, lib/embulk/input/marketo/lead.rb, test/embulk/input/marketo/test_activity_log.rb, test/embulk/input/marketo/test_lead.rb
Raise ConfigError if given URL is invalid before requesting to API.
=> Validate wsdl_url and endpoint_url are the valid form

embulk-input-marketo.gemspec
Cannot regenerate CODECLIMATE_REPO_TOKEN
https://github.com/codeclimate/ruby-test-reporter/issues/97
=> Fix to use CodeClimate 0.x

src/main/java/org/embulk/input/marketo/MarketoService.java, src/main/java/org/embulk/input/marketo/MarketoServiceImpl.java, src/main/java/org/embulk/input/marketo/MarketoUtils.java, src/main/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPlugin.java, src/main/java/org/embulk/input/marketo/model/BulkExtractRangeHeader.java, src/main/java/org/embulk/input/marketo/rest/MarketoBaseRestClient.java, src/main/java/org/embulk/input/marketo/rest/MarketoInputStreamResponseEntityReader.java, src/main/java/org/embulk/input/marketo/rest/MarketoResponseJetty92EntityReader.java, src/main/java/org/embulk/input/marketo/rest/MarketoRestClient.java, src/test/java/org/embulk/input/marketo/MarketoServiceImplTest.java, src/test/java/org/embulk/input/marketo/delegate/ActivityBulkExtractInputPluginTest.java, src/test/java/org/embulk/input/marketo/delegate/CampaignInputPluginTest.java, src/test/java/org/embulk/input/marketo/delegate/LeadBulkExtractInputPluginTest.java, src/test/java/org/embulk/input/marketo/delegate/LeadWithListInputPluginTest.java, src/test/java/org/embulk/input/marketo/delegate/LeadWithProgramInputPluginTest.java, src/test/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPluginTest.java, src/test/java/org/embulk/input/marketo/rest/MarketoBaseRestClientTest.java, src/test/java/org/embulk/input/marketo/rest/MarketoRestClientTest.java
- Fix issue when there is field that is only available in REST describe
schema
- Change lead get method to POST and use _method=GET as suggested by
Marketo. This will help prevent the URI too long issue when lead schema
have too many fields.
- Add retry in Marketo saveFile since it could be failed midway.
- Add EOFException to retry exception.
- Change generation next config diff from_date generation logic to use
latest_fetch_time instead of always to_date since Marketo will cut off
the result if extract file result is bigger than 500MB.
- Fix an issue that will cause OutOfMemory execption when there is too
many list and lead schema have too many fields.
- Make import all_lead_with_list_id all_lead_with_program_id lazy
=> Marketo input hot fixes

CHANGELOG.md, build.gradle, src/main/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPlugin.java, src/test/java/org/embulk/input/marketo/delegate/ActivityBulkExtractInputPluginTest.java, src/test/java/org/embulk/input/marketo/delegate/LeadBulkExtractInputPluginTest.java, src/test/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPluginTest.java
=> Remove deduplication logic

CHANGELOG.md, README.md, build.gradle
=> Release v0.6.10

README.md, src/main/java/org/embulk/input/marketo/CsvTokenizer.java, src/main/java/org/embulk/input/marketo/MarketoInputPluginDelegate.java, src/main/java/org/embulk/input/marketo/MarketoService.java, src/main/java/org/embulk/input/marketo/MarketoServiceImpl.java, src/main/java/org/embulk/input/marketo/delegate/LeadBulkExtractInputPlugin.java, src/main/java/org/embulk/input/marketo/delegate/LeadWithListInputPlugin.java, src/main/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPlugin.java, src/main/java/org/embulk/input/marketo/delegate/MarketoBaseInputPluginDelegate.java, src/main/java/org/embulk/input/marketo/delegate/ProgramInputPlugin.java, src/main/java/org/embulk/input/marketo/rest/MarketoBaseRestClient.java, src/main/java/org/embulk/input/marketo/rest/MarketoRESTEndpoint.java, src/main/java/org/embulk/input/marketo/rest/MarketoRestClient.java, src/test/java/org/embulk/input/marketo/delegate/ActivityBulkExtractInputPluginTest.java, src/test/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPluginTest.java, src/test/java/org/embulk/input/marketo/delegate/ProgramInputPluginTest.java, src/test/java/org/embulk/input/marketo/rest/MarketoRestClientTest.java
=> Asset program support

src/main/java/org/embulk/input/marketo/rest/MarketoBaseRestClient.java, src/test/java/org/embulk/input/marketo/rest/MarketoBaseRestClientTest.java
=> Add more error code to retry

CHANGELOG.md, build.gradle
=> Release v0.6.13

src/main/java/org/embulk/input/marketo/delegate/ActivityBulkExtractInputPlugin.java, src/main/java/org/embulk/input/marketo/delegate/LeadBulkExtractInputPlugin.java
Currently the temp file created by Embulk via `Exec.getTempFileSpace().createTempFile(DEFAULT_FILE_FORMAT)`, but when temp not found, we wrapped it with DataExeption.
Should return `RuntimeException` to distinguish with actual data error
=> Improve Exception Handling

src/main/java/org/embulk/input/marketo/delegate/ActivityBulkExtractInputPlugin.java
=> Hotfix issue actTypeIds is required

CHANGELOG.md, README.md, build.gradle, src/main/java/org/embulk/input/marketo/MarketoService.java, src/main/java/org/embulk/input/marketo/delegate/ActivityBulkExtractInputPlugin.java, src/main/java/org/embulk/input/marketo/delegate/LeadBulkExtractInputPlugin.java, src/main/java/org/embulk/input/marketo/rest/MarketoBaseRestClient.java, src/main/java/org/embulk/input/marketo/rest/MarketoRestClient.java, src/test/java/org/embulk/input/marketo/delegate/ActivityBulkExtractInputPluginTest.java, src/test/java/org/embulk/input/marketo/rest/MarketoBaseRestClientTest.java
=> Support Marketo partner API Key

build.gradle, src/main/java/org/embulk/input/marketo/delegate/ProgramMembersBulkExtractInputPlugin.java
=> Support program members

build.gradle
=> Follows the PR #114 bump up v0.6.25

build.gradle
`javadoc` and `sources` JARs are mandatory for Maven Central.
=> Get ready for Maven Central by adding sources and javadoc JARs

.github/workflows/build.yml
=> Update coverage location

CHANGELOG.md, README.md, build.gradle, src/main/java/org/embulk/input/marketo/CsvTokenizer.java, src/test/java/org/embulk/input/marketo/CsvTokenizerTest.java, src/test/java/org/embulk/input/marketo/delegate/LeadBulkExtractInputPluginTest.java, src/test/resources/fixtures/lead_extract_with_quote_RFC4180.csv, src/test/resources/fixtures/lead_extract_with_quote_in_quote_field.csv
=> INTEG-2699 Marketo Input support QuotesInQuotedFields

CHANGELOG.md, build.gradle, src/main/java/org/embulk/input/marketo/rest/MarketoRestClient.java
=> INTEG-2768: Add requestId to logs and enable access to received JSON files in Marketo Import Integration
