- lib/embulk/input/marketo_api/soap.rb
- test/embulk/input/test_marketo.rb
Use logger for SOAP requests information display.
Sample output:
```
2015-07-06 11:27:07.567 +0900: Embulk v0.6.15
2015-07-06 11:27:10.834 +0900 [INFO] (transaction): Loaded plugin embulk-input-marketo (0.0.1)
2015-07-06 11:27:10.908 +0900 [INFO] (transaction): {done:  0 / 1, running: 0}
2015-07-06 11:27:10.945 +0900 [INFO] (task-0000): Writing local file './sample000.00..csv'
2015-07-06 11:27:13.168 +0900 [INFO] (task-0000): SOAP request: https://****.mktoapi.com/soap/mktows/2_9
2015-07-06 11:27:13.168 +0900 [INFO] (task-0000): SOAPAction: "http://www.marketo.com/mktows/getMultipleLeads", Content-Type: text/xml;charset=UTF-8, Content-Length: 809
2015-07-06 11:27:30.201 +0900 [INFO] (task-0000): SOAP response (status 200)
2015-07-06 11:27:30.329 +0900 [INFO] (task-0000): Remaining …
```
> Add logger into around Marketo API requests

- lib/embulk/input/marketo_api/soap.rb
- test/embulk/input/marketo_api/test_soap.rb
- test/embulk/input/test_marketo.rb
Sometimes Marketo SOAP API returns 500 (SOAP 20016 error).
That means "signature is too old", so use fresh signature in every request.
> Avoid 500 error

- README.md
- lib/embulk/input/marketo/base.rb
- lib/embulk/input/marketo/lead.rb
- lib/embulk/input/marketo/timeslice.rb
- lib/embulk/input/marketo_api/soap/base.rb
- lib/embulk/input/marketo_api/soap/lead.rb
- lib/embulk/input/marketo_api/soap/timeslice.rb
- test/embulk/input/marketo/test_lead.rb
- test/embulk/input/marketo_api/soap/test_lead.rb
- test/mute_logger.rb
:fallen_leaf: Some breaking changes including as described on README. :fallen_leaf: 
Each request takes ~30 seconds on my tests (before this change ~2 minutes).
But whole process throughput is slightly decreased before this changes.
We'll make this plugin to work in multithreading after this PR merged for more speed.
> Avoid timeout for marketo/lead input

- lib/embulk/input/marketo/activity_log.rb
- lib/embulk/input/marketo_api/soap/activity_log.rb
- test/activity_log_fixtures.rb
- test/embulk/input/marketo/test_activity_log.rb
- test/embulk/input/marketo_api/soap/test_activity_log.rb
`activity_date_time` was Time.parse-ed twice (on `fetch`, and before `page_builder.add`) that caused error at 2nd Time.parse.
This PR fixes that `fetch` don't care for each column type. It *passed* as Time object, but *now passing* String object.
> Fix handling for activity_date_time

- .travis.yml
- gemfiles/embulk-0.6.26
- lib/embulk/input/marketo/activity_log.rb
- lib/embulk/input/marketo/lead.rb
- lib/embulk/input/marketo/timeslice.rb
- test/embulk/input/marketo/test_activity_log.rb
- test/embulk/input/marketo/test_lead.rb
This plugin should raise `ConfigError` when failing Time.parse.
> Catch config error

- lib/embulk/input/marketo/lead.rb
- lib/embulk/input/marketo/timeslice.rb
- test/embulk/input/marketo/test_lead.rb
When `from_datetime` / `to_datetime` are same, `#run` isn't called, so `.resume` returns `[]` (expected non-zero size Array object) as `commit_reports`.
When `commit_reports` is empty, this plugin crashes because `.resume` `commit_reports` returns `nil` but Embulk transaction phase can't treat it.
> Fix the bug when from and to is same

- lib/embulk/input/marketo/lead.rb
- test/embulk/input/marketo/test_lead.rb
We use last_updated_at to get multiple leads, so scheduled execution may fetch duplicated leads in from/to generated by commit report.
> Unsupport scheduled execution for lead

- lib/embulk/input/marketo/activity_log.rb
- lib/embulk/input/marketo/lead.rb
- lib/embulk/input/marketo_api/soap/activity_log.rb
- lib/embulk/input/marketo_api/soap/lead.rb
- test/activity_log_fixtures.rb
- test/embulk/input/marketo/test_activity_log.rb
- test/embulk/input/marketo/test_lead.rb
- test/embulk/input/marketo_api/soap/test_activity_log.rb
- test/embulk/input/marketo_api/soap/test_lead.rb
- test/lead_fixtures.rb
- test/savon_helper.rb
- Use XPath on both lead and activity_log. Using hash is ambiguous than XPath e.g. `<a><b>hi</b></a>` and `<a><b>hi</b><b>hello</b></a>`, first one will be cast as  `{a: {b: "hi"} }`, second one will be  `{a: {b: ["hi", "hello"]}}`
- Mocking Savon::Response on test
- Some large method separation
> Refactor lead and activity

- lib/embulk/input/marketo/base.rb
- test/embulk/input/marketo/test_activity_log.rb
Sometimes Marketo returns empty timestamp string.
We treat it as `nil` instead of raising error.
> Recognize empty string as nil value

- embulk-input-marketo.gemspec
- lib/embulk/input/marketo_api/soap/activity_log.rb
- lib/embulk/input/marketo_api/soap/base.rb
- lib/embulk/input/marketo_api/soap/lead.rb
- test/embulk/input/marketo_api/soap/test_base.rb
- Raise original error instead of TooManyRetry error
- Reduce redundant log
- Don't show Savon request log
- Some trivial information log level to `debug` from `info`
> Make debug easier

- lib/embulk/input/marketo/activity_log.rb
- test/activity_log_fixtures.rb
- test/embulk/input/marketo/test_activity_log.rb
Before this commit, config_diff was generated only some records found.
It is non-friendly for a batch job.
> Generate config_diff even if no records found

- embulk-input-marketo.gemspec
- lib/embulk/input/marketo_api/soap/base.rb
Sometimes waiting a response is a long time enough to be killed by NAT.
This PR enables TCP Keepalive to protect a long time session.
> Enable tcp keepalive

- src/main/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPlugin.java
- src/test/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPluginTest.java
- src/test/java/org/embulk/input/marketo/rest/MarketoRestClientTest.java
Fix NullPointerException in buildConfigDiff when there is no data
returned.
Make toDate equal job start time when it's bigger than jobStartTime.toDate was previously capped to be smaller then job start time minus 1
hours.
Add validation to make sure from_date must be smaller than current time
> Fix NullPointerException in buildConfigDiff

- build.gradle
- src/main/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPlugin.java
Skip record with smaller timestamp that latest_fetch_time. Marketo API
returned record that have smaller timestamp that in query. This cause
incorrect incremental time generated when process those record.
> Add timestamp check with latest_fetch_time

- src/main/java/org/embulk/input/marketo/rest/MarketoRestClient.java
- src/test/java/org/embulk/input/marketo/rest/MarketoRestClientTest.java
Move now time to loop
Update unit test
> PLT-9086: Incorrect job timeout calculation

- src/main/java/org/embulk/input/marketo/rest/MarketoRestClient.java
- src/test/java/org/embulk/input/marketo/rest/MarketoRestClientTest.java
Move now time to loop
Update unit test
> Fix incorrect job timeout calculation

- src/main/java/org/embulk/input/marketo/rest/MarketoBaseRestClient.java
- src/test/java/org/embulk/input/marketo/rest/MarketoBaseRestClientTest.java
Redundant content type are set and force all post request to use
application/json data type which cause Marketo to ignore nextPageToken
parameter and return the same token
> Fix infinite loop in non bulk extract target

- src/main/java/org/embulk/input/marketo/delegate/MarketoBaseInputPluginDelegate.java
MarketoBaseInputPluginDelegate open Jetty92RetryHelper and didn't close
it. This cause plugin to hang.
> Fix JettyRetryHelper not closed

- build.gradle
- src/main/java/org/embulk/input/marketo/rest/MarketoBaseRestClient.java
- src/test/java/org/embulk/input/marketo/TestMarketoInputPlugin.java
- src/test/java/org/embulk/input/marketo/rest/MarketoBaseRestClientTest.java
> Fix incorrect retry

- src/main/java/org/embulk/input/marketo/MarketoInputPluginDelegate.java
- src/main/java/org/embulk/input/marketo/delegate/MarketoBaseInputPluginDelegate.java
- src/main/java/org/embulk/input/marketo/rest/MarketoBaseRestClient.java
- src/main/java/org/embulk/input/marketo/rest/MarketoRestClient.java
- src/test/java/org/embulk/input/marketo/rest/MarketoBaseRestClientTest.java
* Fix when TimeoutException is wrapped in IOException it won't get retried.
* Increase read timeout to 60 seconds
* Make read timeout configurable
* Increase max_retry times to 7
* Remove uneccessary configuration in delegate.
* Update unit tests
> Fix wrapped TimeoutException not retried

- src/main/java/org/embulk/input/marketo/MarketoService.java
- src/main/java/org/embulk/input/marketo/MarketoServiceImpl.java
- src/main/java/org/embulk/input/marketo/MarketoUtils.java
- src/main/java/org/embulk/input/marketo/delegate/LeadBulkExtractInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/LeadServiceResponseMapperBuilder.java
- src/main/java/org/embulk/input/marketo/delegate/LeadWithListInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/LeadWithProgramInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/MarketoBaseInputPluginDelegate.java
- src/main/java/org/embulk/input/marketo/model/MarketoField.java
- src/main/java/org/embulk/input/marketo/rest/MarketoRestClient.java
- src/test/java/org/embulk/input/marketo/MarketoServiceImplTest.java
- src/test/java/org/embulk/input/marketo/delegate/LeadServiceResponseMapperBuilderTest.java
- src/test/java/org/embulk/input/marketo/rest/MarketoRestClientTest.java
Move all lead ServiceResponseMapper logic to 1 class
Move preview record limit to it right place
Add included column option
> Add included column option

- .travis.yml
- src/main/java/org/embulk/input/marketo/delegate/CustomObjectInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/CustomObjectResponseMapperBuilder.java
- src/main/java/org/embulk/input/marketo/delegate/ProgramInputPlugin.java
- src/main/java/org/embulk/input/marketo/rest/MarketoBaseRestClient.java
- src/test/java/org/embulk/input/marketo/delegate/CustomObjectInputPluginTest.java
- src/test/java/org/embulk/input/marketo/delegate/ProgramInputPluginTest.java
- src/test/java/org/embulk/input/marketo/rest/MarketoBaseRestClientTest.java
Current code doesn't count on the HttpResponseException. When the server responses with code do not equal 200 it simply throws the exception up to Embulk.
This fix will wrap all API call and when the HttpResponseException occurred will re-throw with ConfigException or DataException instead.
> Improve error handler

- CHANGELOG.md
- README.md
- build.gradle
- src/main/java/org/embulk/input/marketo/MarketoService.java
- src/main/java/org/embulk/input/marketo/MarketoServiceImpl.java
- src/main/java/org/embulk/input/marketo/delegate/CustomObjectInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/LeadWithListInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/LeadWithProgramInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/MarketoBaseInputPluginDelegate.java
- src/main/java/org/embulk/input/marketo/rest/MarketoRestClient.java
- src/test/java/org/embulk/input/marketo/MarketoServiceImplTest.java
- src/test/java/org/embulk/input/marketo/delegate/CustomObjectInputPluginTest.java
- src/test/java/org/embulk/input/marketo/delegate/LeadWithListInputPluginTest.java
- src/test/java/org/embulk/input/marketo/delegate/LeadWithProgramInputPluginTest.java
- src/test/java/org/embulk/input/marketo/delegate/MarketoBaseInputPluginDelegateTest.java
- src/test/java/org/embulk/input/marketo/rest/MarketoRestClientTest.java
> Support import subset of Leads by provided Lists Ids or Program Ids

- .github/workflows/build.yml
- .travis.yml
- CHANGELOG.md
- build.gradle
- src/main/java/org/embulk/input/marketo/MarketoUtils.java
- src/main/java/org/embulk/input/marketo/delegate/ActivityBulkExtractInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/LeadBulkExtractInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPlugin.java
- src/main/java/org/embulk/input/marketo/delegate/MarketoBaseInputPluginDelegate.java
- src/main/java/org/embulk/input/marketo/delegate/ProgramInputPlugin.java
- src/test/java/org/embulk/input/marketo/MarketoUtilsTest.java
- src/test/java/org/embulk/input/marketo/delegate/ActivityBulkExtractInputPluginTest.java
- src/test/java/org/embulk/input/marketo/delegate/LeadBulkExtractInputPluginTest.java
- src/test/java/org/embulk/input/marketo/delegate/MarketoBaseBulkExtractInputPluginTest.java
- src/test/java/org/embulk/input/marketo/delegate/ProgramInputPluginTest.java
- src/test/java/org/embulk/input/marketo/rest/MarketoRestClientTest.java
**Summary:**
-  Replace Joda-Time with java.time classes.
-  Use GitHub Action instead of Travis CI.
> Replace Joda-Time with java.time classes

- CHANGELOG.md
- src/main/java/org/embulk/input/marketo/delegate/ProgramMembersBulkExtractInputPlugin.java
- src/test/java/org/embulk/input/marketo/delegate/ProgramMembersBulkExtractInputPluginTest.java
> Fix resource leak when import program members

- CHANGELOG.md
- build.gradle
- src/main/java/org/embulk/input/marketo/rest/MarketoInputStreamResponseEntityReader.java
> Fix issue response header Marketo change from text/csv to text/csv;charset=UTF-8

- .github/workflows/build.yml
From https://github.com/actions/upload-artifact?tab=readme-ov-file#actionsupload-artifact
```
Warning
actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) Similarly, v1/v2 are scheduled for deprecation on June 30, 2024. Please update your workflow to use v4 of the artifact actions. This deprecation will not impact any existing versions of GitHub Enterprise Server being used by customers.
```
We will need to update our version
> Update upload artifact to v4
